### ISSUE TITLE
Using gatsby-remark-picture with gatsby-image

### ISSUE THREAD

**Issue by robinmetral** [xuopled/gatsby-remark-picture#1]
Hi :wave:, and thanks for this plugin!

I'd like to wrap my `<img>` tags in the more semantic `<picture>` tag, but I'm already using `gatsby-remark-images` (a remark plugin for `gatsby-image`) to handle generating responsive images as well as base64 placeholders.

Can I use this plugin only to wrap my `gatsby-remark-image` markup in a `<picture>` tag?

**Comment by bever1337** [comment]
@robinmetral  Instead of using `gatsby-remark-images` or `gatsby-image`, you can use JUST `gatsby-remark-picture`. All of these plugins are using `gatsby-plugin-sharp` under the hood so you are guaranteed the same source content. You can verify this with some graphql queries.

Disclaimer: I'm not a contributor to `gatsby-remark-picture`.

In my own use, `gatsby-remark-image` was tedious because I had almost zero control over styling and the html syntax was confusing. `gatbsy-image` is great but introduces code complexity in the form of extensive graphql fragments which cannot be dynamically generated, or complicated md transformer plugin chaining using things like `gatsby-remark-component` and writing JSX in your md files.

Using `gatsby-remark-picture`, I can write very plain md that source images with relative paths. For example,

```
---
title: 'bio title'
category: 'about'
---

# bio page

look at this post

![alt text](coffee.jpg 'a picture of coffee')![alt text](coffee.jpg 'another picture of coffee')
```

Then using this plugin configuration:
```
    ...
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          // Optional: Remove the paragraph tag wrapping images
          'gatsby-remark-unwrap-images',
          // Wrap images by pictures
          'gatsby-remark-picture',
        ],
      },
    },
    ...
```

Now my React components are beautifully clean:

```
import React from 'react';
import rehypeReact from 'rehype-react';

const renderAst = new rehypeReact({
  createElement: React.createElement,
}).Compiler;

const Post = props => (<article>{renderAst(props.pageContext.htmlAst)}</article>);
```

End result: Full support for sharp images with fluid widths, complete control over styling, no complicated data queries, all images can be sourced via plain markdown. I sincerely believe this is the best sharp plugin in the Gatsby ecosystem. Again, not a contributor just a fan!

```
<article>
<h1>bio page</h1>
<p>look at this post</p>
<picture><img src="/static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg" alt="alt text" title="one" srcset="/static/bcb73e8e155009aeb56079804bbc4d2a/977f7/coffee.jpg 200w, /static/bcb73e8e155009aeb56079804bbc4d2a/2db5b/coffee.jpg 400w, /static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg 612w" sizes="(max-width: 612px) 100vw, 612px"></picture>
<picture><img src="/static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg" alt="alt text" title="two" srcset="/static/bcb73e8e155009aeb56079804bbc4d2a/977f7/coffee.jpg 200w, /static/bcb73e8e155009aeb56079804bbc4d2a/2db5b/coffee.jpg 400w, /static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg 612w" sizes="(max-width: 612px) 100vw, 612px"></picture>
</article>
```

**Comment by bever1337** [comment]
Unrelated to this plugin, but to avoid the extra `<div>` tag that rehype-react wraps around htmlAst content, I do something like this `renderAst(page).props.children`

@robinmetral I am realizing for a large, established project it might represent a lot of change to strip out all the other stuff. If you are `using rehype-react` but can't afford switching to `gatsby-remark-picture`, you can also programmatically change the element type provided by the AST by providing a map in the compiler options.

**Comment by robinmetral** [comment]
@bbboydston thanks for your replies!

One thing I love with `gatsby-image` is that it can generate a base64 placeholder image, and I don't think `gatsby-remark-picture` does this :pensive:

**Comment by bever1337** [comment]
@robinmetral 

The base64 placeholder is generated for all the sharp plugins, `gatsby-remark-picture` is no exception here. You can verify with this query:

```
{
  allImageSharp {
    edges {
      node {
        fluid {
          base64
        } 
        original {
          width
          height
          src
        }
      }
    }
  }
}
```

Some solutions might be:
- You could use `react-rehype` to wrap a `<div />` around your `<picture />` elements, and then use the base64 image as background-image src.
- You could use `gatsby-remark-custom-blocks` which allows you to insert divs into markdown with an extended syntax, and then use base64 image as a background-image src.
- Make a PR to this plugin.

I just did a real quick test, modifying the index.js of `gatsby-remark-picture`, and was able to get a background-image sourced from base64 into the DOM. If your project is setup for git, maybe you can diff the original and this edit to see what I did? It was very easy.

```
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };

require(`gatsby/dist/redux/actions`);

const visit = require(`unist-util-visit`);
const path = require(`path`);
const isRelativeUrl = require(`is-relative-url`);
const { fluid } = require(`gatsby-plugin-sharp`);
const slash = require(`slash`);
const Promise = require(`bluebird`);
const util = require('util');
module.exports = ({ files, markdownNode, markdownAST, getNode, reporter }, pluginOptions) => {
  const getResponsiveSources = async function (node, resolve, reject) {
    const folderNode = getNode(markdownNode.parent);

    if (!folderNode || !folderNode.dir) {
      resolve();
    }

    const imagePath = slash(path.join(folderNode.dir, node.url));
    const imageNode = files.find(file => file && file.absolutePath && file.absolutePath === imagePath);

    if (typeof imageNode === undefined) {
      resolve();
    }

    const source = await fluid({
      file: imageNode,
      reporter
    });
    // console.log('\n--------\nawaited fluid', source);

    const sourceWebp = pluginOptions.withSourceWebp && (await fluid({
      file: imageNode,
      args: { toFormat: `WEBP` },
      reporter
    }));

    return { source, sourceWebp };
  };

  let markdownImageNodes = [];

  visit(markdownAST, `image`, (node, index, parent) => {
    markdownImageNodes.push(node);
  });

  return Promise.all(markdownImageNodes.map(node => new Promise(async (resolve, reject) => {
    if (isRelativeUrl(node.url)) {
      const { source, sourceWebp } = await getResponsiveSources(node, resolve, reject);
      console.log('\n------------\nMARKDOWN IMAGE NODE', source.base64);
      const imageNode = Object.assign({}, node, source ? {
        data: _extends({}, node.data ? node.data : {}, {
          hProperties: _extends({}, node.data && node.data.hProperties ? node.data.hProperties : {}, {
            src: source.src,
            srcset: source.srcSet,
            sizes: source.sizes,
            base64: source.base64,
          })
        })
      } : {});

      const sourceNode = pluginOptions.withSource && source && {
        type: "paragraph",
        data: {
          hName: "source",
          hProperties: {
            srcset: source.srcSet,
            sizes: source.sizes,
            type: source.srcSetType,
            base64: source.base64,
          }
        }
      };

      const sourceWebpNode = sourceWebp && {
        type: "paragraph",
        data: {
          hName: "source",
          hProperties: {
            srcset: sourceWebp.srcSet,
            sizes: sourceWebp.sizes,
            type: sourceWebp.srcSetType,
            base64: source.base64,
          }
        }
      };

      node.type = "paragraph";
      node.data = {
        hName: "picture",
        hProperties: _extends({
          style: "display: block;background-image: url("+source.base64+");",
        }, pluginOptions.className ? { className: pluginOptions.className } : {})
      };

      node.children = [...(sourceWebpNode ? [sourceWebpNode] : []), ...(sourceNode ? [sourceNode] : []), imageNode];
      console.log('\nRESOLVING:\n', util.inspect(node, {depth: null}));
      resolve(node);
    } else {
      resolve();
    }
  })));
};
```

Results in:
```
<picture style="border: 5px solid pink; background-image: url(&quot;data:image/jpeg;base64,base 64 bytes removed"><img src="/static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg" alt="alt text" title="one" srcset="/static/bcb73e8e155009aeb56079804bbc4d2a/977f7/coffee.jpg 200w, /static/bcb73e8e155009aeb56079804bbc4d2a/2db5b/coffee.jpg 400w, /static/bcb73e8e155009aeb56079804bbc4d2a/f16bf/coffee.jpg 612w" sizes="(max-width: 612px) 100vw, 612px" base64="data:image/jpeg;base64,base 64 bytes removed"></picture>
```

**Comment by bever1337** [comment]
@xuopled What are you thinking of this idea? That code example is very rough, for example I am leery of applying default styles like turning pictures into block-level elements, but @robinmetral makes a good point that the base64 background feature is prized among sharp users. I'd love to put in a PR after some refactoring.

**Comment by bever1337** [comment]
Sorry for going so comment heavy. I do not think this plugin can achieve the specific result of converting `img` to `picture` elements. So to answer the original Q, this code creates a compiler that'll convert the elements.

```
import React from 'react';
import rehypeReact from 'rehype-react';

const renderAst = new rehypeReact({
  createElement: React.createElement,
  components: { img: 'picture' },
}).Compiler;

export default renderAst;
```

That said, I still think adding base64 support would help capture a larger gatsby audience.

**Comment by cedricdelpoux** [comment]
Wow, thank you for your work and your explainations @bbboydston. Like you said, I had no styling control with `gatsby-remark-image` and `gatbsy-image` was very complex for my need, that why I built this plugin. I was not expecting getting a fan like you with 0 stars 😅 

I didn' t know background image was a power feature of `gatsby-image`.

I would be very glad if you could open a PR with your work 💪🏻

Thank you for spreading the word and make this lib better

**Comment by robinmetral** [comment]
This is great @bbboydston @xuopled! Looking forward to it :100:
